### ISSUE TITLE
The snap version of meshlab is outdated

### ISSUE THREAD

**Issue by lianghongzhuo** [cnr-isti-vclab/meshlab#691]
#### Check all platforms you experienced the issue (change to `[x]`)
- [ ] Windows
- [ ] Every platform
- [X] Linux
- [ ] Mac OS

#### What type of issue is?
- [ ] bug or unexpected behavior
- [ ] crash
- [X] feature request
- [ ] other (specify...)

#### Describe your issue

The snap version of meshlab is outdated. https://snapcraft.io/meshlab
Is there any plan to push the latest binary to the snap store?

Thank you.

**Comment by alemuntoni** [comment]
Hi, it's not a priority at the moment, since we are releasing appimages for linux.
But pull requests for the generation of a snap package are welcome.

**Comment by lianghongzhuo** [comment]
I tried to build a snap using `snapcraft`
I got this error:
```
make[1]: Entering directory '/root/parts/meshlab/build/meshlabplugins/edit_pickpoints'
make[1]: Nothing to be done for 'first'.
make[1]: Leaving directory '/root/parts/meshlab/build/meshlabplugins/edit_pickpoints'
cp -f -R "/root/parts/meshlab/build/src/../distrib" "/root/parts/meshlab/build"
cp: '/root/parts/meshlab/build/src/../distrib' and '/root/parts/meshlab/build/distrib' are the same file
Makefile:1992: recipe for target 'copydir' failed
make: *** [copydir] Error 1
```
It seems that the `copydir` command wants to copy the files with the same orientation and destination.
Any suggestions to fix it?
I'm using ubuntu18, and this is the modified `snapcraf.yaml`

```
name: meshlab
base: core18
version: '2020.05'
summary: MeshLab
description: |
  The open source system for processing and editing 3D triangular meshes.
  It provides a set of tools for editing, cleaning, healing, inspecting,
  rendering, texturing and converting meshes. It offers features for processing
  raw data produced by 3D digitization tools/devices and for preparing models
  for 3D printing.
icon: snap/gui/meshlab.png

grade: stable
confinement: strict

apps:
  meshlab:
    command: desktop-launch meshlab
    plugs: [home, x11, mir, opengl]
  meshlabserver:
    command: desktop-launch meshlabserver
    plugs: [home, x11, opengl]


parts:
  meshlab:
    # after: [desktop-qt5]
    plugin: qmake
    qt-version: qt5
    source: https://github.com/cnr-isti-vclab/meshlab.git
    build-packages:
      - qt5-default
      - qttools5-dev-tools
      - qtscript5-dev
      - libqt5xmlpatterns5-dev
      - mesa-common-dev
      - libglu1-mesa-dev
      - lib3ds-dev
      - libglew-dev
      - libeigen3-dev 
      - libopenctm-dev 
      - libgmp-dev 
      - libqhull-dev
    override-build: |
      qmake src/meshlab.pro "CONFIG+= system_eigen3 system_glew system_bzip2 system_openctm system_lib3ds"
      make -j4
```
